version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - api
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - 8080:80
    restart: on-failure


  api:
    image: api
    container_name: api
    build:
      context: ./api
    ports:
      - 5000:5001
    restart: on-failure
